{
 "title": "🔧 Failure Intelligence",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "station",
    "query": "SELECT DISTINCT station_name \nFROM public.dashboard_overview \nORDER BY station_name;"
   }
  ]
 },
 "panels": [
  {
   "title": "Quality (Target: 85 %)",
   "type": "stat",
   "description": "* Target ≥ 85%\n* Excellent > 85\n* Acceptable 60–85\n* Critical < 60",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  ROUND(AVG(NULLIF(quality_pct,0)),1) AS Quality,\r\n  CASE\r\n    WHEN AVG(NULLIF(quality_pct,0)) < 60 THEN 'CRITICAL'\r\n    WHEN AVG(NULLIF(quality_pct,0)) < 85 THEN 'ACCEPTABLE'\r\n    ELSE 'EXCELLENT'\r\n  END AS Status\r\nFROM public.quality_kpi\r\nWHERE station_name IN (${station:sqlstring})\r\n  AND $__timeFilter(production_day);"
    }
   ]
  },
  {
   "title": "OEE GLOBAL MOYEN",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  AVG(NULLIF(oee_pct, 0)) AS \"OEE Global moyen\"\r\nFROM public.oee_kpi\r\nWHERE station_name IN ($station)\r\n  AND $__timeFilter(production_day);"
    }
   ]
  },
  {
   "title": "Downtime Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT SUM(downtime_hours) AS \"Downtime Total\"\r\nFROM public.downtime_by_station_kpi\r\nWHERE station_name IN ($station)\r\n  AND $__timeFilter(production_day);"
    }
   ]
  },
  {
   "title": "OEE TREND",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  date_trunc('day', production_day::timestamp) AS \"time\",\r\n  AVG(oee_pct) AS \"OEE\"\r\nFROM public.oee_kpi\r\nWHERE station_name IN ($station)\r\n  AND $__timeFilter(production_day::timestamp)\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "MTTR (Reliability)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT AVG(mttr_hours) AS \"MTTR\"\r\nFROM public.mttr_kpi\r\nWHERE mttr_hours IS NOT NULL\r\n  AND mttr_hours > 0;"
    }
   ]
  },
  {
   "title": "PERFORMANCE ( Target: 85% )",
   "type": "stat",
   "description": "* Target ≥ 85%\n* Excellent > 85\n* Acceptable 60–85\n* Critical < 60",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  ROUND(AVG(NULLIF(performance_pct,0)),1) AS Performance,\r\n  CASE\r\n    WHEN AVG(NULLIF(performance_pct,0)) < 60 THEN 'CRITICAL'\r\n    WHEN AVG(NULLIF(performance_pct,0)) < 85 THEN 'ACCEPTABLE'\r\n    ELSE 'EXCELLENT'\r\n  END AS Status\r\nFROM public.performance_kpi\r\nWHERE station_name IN ($station)\r\n  AND $__timeFilter(production_day);"
    }
   ]
  },
  {
   "title": "MTBF(Reliability)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT AVG(mtbf_hours) AS \"MTBF\"\r\nFROM public.mtbf_kpi\r\nWHERE mtbf_hours IS NOT NULL\r\n  AND mtbf_hours > 0;"
    }
   ]
  },
  {
   "title": "OEE COMPONENTS TREND",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 9 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  date_trunc('day', production_day::timestamp) AS \"time\",\r\n  AVG(NULLIF(availability_pct, 0)) AS \"Availability %\",\r\n  AVG(NULLIF(performance_pct, 0)) AS \"Performance %\",\r\n  AVG(NULLIF(quality_pct, 0)) AS \"Quality %\"\r\nFROM public.dashboard_overview\r\nWHERE station_name IN ($station)\r\n  AND oee_pct > 0\r\n  AND $__timeFilter(production_day::timestamp)\r\nGROUP BY 1\r\nORDER BY 1 ASC;"
    }
   ]
  },
  {
   "title": "AVAILABILTY ( Target: 85% )",
   "type": "stat",
   "description": "* Excellent > 85\n* Acceptable 60–85\n* Critical < 60",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  ROUND(AVG(NULLIF(availability_pct,0)),1) AS Availability,\r\n  CASE\r\n    WHEN AVG(NULLIF(availability_pct,0)) < 60 THEN 'CRITICAL'\r\n    WHEN AVG(NULLIF(availability_pct,0)) < 85 THEN 'ACCEPTABLE'\r\n    ELSE 'EXCELLENT'\r\n  END AS Status\r\nFROM public.availability_kpi\r\nWHERE station_name IN ($station)\r\n  AND $__timeFilter(production_day);"
    }
   ]
  }
 ]
}