{
 "title": "📊PERFORMANCE ANALYTICS ",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "line",
    "query": "SELECT name FROM staging.lines ORDER BY name"
   },
   {
    "name": "station",
    "query": "select distinct station_name from public.performance_kpi;"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n  ROUND(AVG(performance_pct)::numeric, 2) AS performance_global,\r\n  ROUND(MIN(performance_pct)::numeric, 2) AS \"Min\",\r\n  ROUND(MAX(performance_pct)::numeric, 2) AS \"Max\"\r\nFROM public.performance_kpi\r\nWHERE station_name IN (\r\n    SELECT s.name FROM staging.stations s\r\n    JOIN staging.line_stations ls ON ls.station_id = s.id\r\n    JOIN staging.lines l ON l.id = ls.line_id\r\n    WHERE l.name IN (${line:sqlstring})\r\n  )\r\n  AND $__timeFilter(production_day);"
    }
   ]
  },
  {
   "title": "Run Time Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n    ROUND(SUM(run_time_hours)::numeric, 0) AS \"Run Time\"\r\nFROM public.mtbf_kpi\r\nWHERE station_name IN (\r\n  SELECT s.name FROM staging.stations s\r\n  JOIN staging.line_stations ls ON ls.station_id = s.id\r\n  JOIN staging.lines l ON l.id = ls.line_id\r\n  WHERE l.name IN (${line:sqlstring})\r\n)"
    }
   ]
  },
  {
   "title": "Micro Stop Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n  ROUND(SUM(micro_stop_hours)::numeric, 2) AS micro_stop_hours\r\nFROM public.performance_kpi\r\nWHERE station_name IN (\r\n    SELECT s.name FROM staging.stations s\r\n    JOIN staging.line_stations ls ON ls.station_id = s.id\r\n    JOIN staging.lines l ON l.id = ls.line_id\r\n    WHERE l.name IN (${line:sqlstring})\r\n  )\r\n  AND $__timeFilter(production_day);"
    }
   ]
  },
  {
   "title": "Performance Status Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n    station_name AS \"Station\",\r\n    ROUND(AVG(performance_pct)::numeric, 1) AS \"Performance %\",\r\n    ROUND(SUM(run_time_hours)::numeric, 0) AS \"Run Time (h)\",\r\n    ROUND(SUM(micro_stop_hours)::numeric, 0) AS \"Micro Stop (h)\",\r\n    CASE\r\n        WHEN AVG(performance_pct) >= 85 THEN '✅ Excellent'\r\n        WHEN AVG(performance_pct) >= 70 THEN '🟢 Good'\r\n        WHEN AVG(performance_pct) >= 60 THEN '🟡 Acceptable'\r\n        ELSE '🔴 Critical'\r\n    END AS \"Status\"\r\nFROM public.performance_kpi\r\nGROUP BY station_name\r\nORDER BY AVG(performance_pct) DESC;"
    }
   ]
  },
  {
   "title": "Performance by Station",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  station_name AS station,\r\n  ROUND(AVG(performance_pct)::numeric, 2) AS performance_pct\r\nFROM public.performance_kpi\r\nWHERE station_name IN (\r\n  SELECT s.name FROM staging.stations s\r\n  JOIN staging.line_stations ls ON ls.station_id = s.id\r\n  JOIN staging.lines l ON l.id = ls.line_id\r\n  WHERE l.name IN (${line:sqlstring})\r\n)\r\nAND $__timeFilter(production_day)\r\nGROUP BY station_name\r\nORDER BY performance_pct DESC;"
    }
   ]
  },
  {
   "title": "Performance Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "WITH daily AS (\r\n    SELECT \r\n        production_day,\r\n        AVG(performance_pct) AS daily_perf\r\n    FROM public.oee_kpi\r\n    WHERE station_name IN (\r\n        SELECT s.name FROM staging.stations s\r\n        JOIN staging.line_stations ls ON ls.station_id = s.id\r\n        JOIN staging.lines l ON l.id = ls.line_id\r\n        WHERE l.name IN (${line:sqlstring})\r\n        )\r\n      AND $__timeFilter(production_day)\r\n    GROUP BY production_day\r\n)\r\nSELECT \r\n    production_day AS time,\r\n    daily_perf AS \"Daily Performance\",\r\n    AVG(daily_perf) OVER (\r\n        ORDER BY production_day\r\n        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW\r\n    ) AS \"7-Day Moving Average\",\r\n    MIN(daily_perf) OVER () AS \"Min\",\r\n    MAX(daily_perf) OVER () AS \"Max\"\r\nFROM daily\r\nORDER BY production_day;"
    }
   ]
  },
  {
   "title": "Run Time vs Micro Stop",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  production_day AS time,\r\n  ROUND(SUM(run_time_hours)::numeric, 2) AS run_time,\r\n  ROUND(SUM(micro_stop_hours)::numeric, 2) AS micro_stop,\r\n  ROUND(MIN(run_time_hours) OVER ()::numeric, 2) AS \"Min Run Time\",\r\n  ROUND(MAX(run_time_hours) OVER ()::numeric, 2) AS \"Max Run Time\"\r\nFROM public.performance_kpi\r\nWHERE station_name IN (\r\n    SELECT s.name FROM staging.stations s\r\n    JOIN staging.line_stations ls ON ls.station_id = s.id\r\n    JOIN staging.lines l ON l.id = ls.line_id\r\n    WHERE l.name IN (${line:sqlstring})\r\n  )\r\n  AND $__timeFilter(production_day)\r\nGROUP BY production_day, run_time_hours\r\nORDER BY production_day;"
    }
   ]
  }
 ]
}