{
 "title": "🚨 Production Alert Center ",
 "time": { "from": "2025-11-13T00:00:00.000Z", "to": "2026-05-11T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "line",
    "query": "SELECT name FROM staging.lines ORDER BY name"
   },
   {
    "name": "station",
    "query": "select distinct station_name from public.downtime_by_station_kpi;"
   }
  ]
 },
 "panels": [
  {
   "title": "AI assistant industriel",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    d.station_name,\r\n\r\n    MAX(d.downtime_minutes) AS downtime_minutes,\r\n    MAX(q.defect_rate_pct) AS defect_rate_pct,\r\n    AVG(o.oee_pct) AS oee_pct,\r\n\r\n    CASE\r\n        WHEN MAX(d.downtime_minutes) > 120 THEN '🔴 Critical Downtime'\r\n        WHEN MAX(q.defect_rate_pct) > 8 THEN '🟠 High Defect Rate'\r\n        WHEN AVG(o.oee_pct) < 60 THEN '🟡 Low OEE'\r\n        ELSE '🟢 Normal'\r\n    END AS detected_issue,\r\n\r\n    CASE\r\n        WHEN MAX(d.downtime_minutes) > 120 THEN 'Schedule urgent maintenance inspection'\r\n        WHEN MAX(q.defect_rate_pct) > 8 THEN 'Inspect calibration and production quality'\r\n        WHEN AVG(o.oee_pct) < 60 THEN 'Review production flow efficiency'\r\n        ELSE 'No action required'\r\n    END AS ai_recommendation\r\n\r\nFROM public.downtime_by_station_kpi d\r\n\r\nLEFT JOIN public.defect_rate_kpi q\r\n    ON d.station_name = q.station_name\r\n\r\nLEFT JOIN public.oee_kpi o\r\n    ON d.station_name = o.station_name\r\n\r\nWHERE d.station_name IN (\r\n  SELECT s.name FROM staging.stations s\r\n  JOIN staging.line_stations ls ON ls.station_id = s.id\r\n  JOIN staging.lines l ON l.id = ls.line_id\r\n  WHERE l.name IN (${line:sqlstring})\r\n)\r\nAND (\r\n  '${station}' = '$__all'\r\n  OR d.station_name IN (${station:sqlstring})\r\n)\r\n\r\nGROUP BY d.station_name;"
    }
   ]
  },
  {
   "title": "Active Alerts Counter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT COUNT(*)\r\nFROM public.downtime_by_station_kpi\r\nWHERE downtime_minutes > 60\r\nAND station_name IN (\r\n  SELECT s.name FROM staging.stations s\r\n  JOIN staging.line_stations ls ON ls.station_id = s.id\r\n  JOIN staging.lines l ON l.id = ls.line_id\r\n  WHERE l.name IN (${line:sqlstring})\r\n);"
    }
   ]
  },
  {
   "title": "Top Failing Stations",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    station_name,\r\n    COUNT(*) AS failures\r\nFROM public.failure_loss_diagnostic_kpi \r\nWHERE station_name IN (\r\n  SELECT s.name FROM staging.stations s\r\n  JOIN staging.line_stations ls ON ls.station_id = s.id\r\n  JOIN staging.lines l ON l.id = ls.line_id\r\n  WHERE l.name IN (${line:sqlstring})\r\n)\r\nGROUP BY station_name\r\nORDER BY failures DESC;"
    }
   ]
  },
  {
   "title": "🛑 Current Critical Downtime",
   "type": "gauge",
   "description": "Displays the current maximum downtime for the selected production station.",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    station_name,\r\n    MAX(downtime_minutes) AS downtime\r\nFROM public.downtime_by_station_kpi\r\nWHERE station_name = '${station}'\r\nGROUP BY station_name;"
    }
   ]
  },
  {
   "title": "Quality Incidents",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 4 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    station_name,\r\n    defect_rate_pct,\r\n    production_day  \r\nFROM public.defect_rate_kpi \r\nWHERE defect_rate_pct > 5 \r\nAND station_name IN (\r\n  SELECT s.name FROM staging.stations s\r\n  JOIN staging.line_stations ls ON ls.station_id = s.id\r\n  JOIN staging.lines l ON l.id = ls.line_id\r\n  WHERE l.name IN (${line:sqlstring})\r\n)\r\nORDER BY defect_rate_pct DESC;"
    }
   ]
  },
  { "title": "🚨 Current Alert Status", "type": "alertlist", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 } },
  {
   "title": "OEE Alerts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    production_day,\r\n    AVG(oee_pct) AS avg_oee \r\nFROM public.oee_kpi \r\nWHERE station_name IN (\r\n  SELECT s.name FROM staging.stations s\r\n  JOIN staging.line_stations ls ON ls.station_id = s.id\r\n  JOIN staging.lines l ON l.id = ls.line_id\r\n  WHERE l.name IN (${line:sqlstring})\r\n)\r\nGROUP BY production_day\r\nORDER BY production_day;"
    }
   ]
  }
 ]
}