{
 "title": "🎯 QUALITY ANALYTICS ",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "line",
    "query": "SELECT name FROM staging.lines ORDER BY name"
   },
   {
    "name": "station",
    "query": "SELECT DISTINCT name\nFROM staging.stations order by name"
   }
  ]
 },
 "panels": [
  {
   "title": "Defect Rate ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    MIN(defect_rate_pct) AS \"Min\",\r\n    ROUND(AVG(defect_rate_pct),2) AS \"Moyen\",\r\n    MAX(defect_rate_pct) AS \"Max\"\r\nFROM public.defect_rate_kpi\r\nWHERE station_name IN (\r\n  SELECT s.name FROM staging.stations s\r\n  JOIN staging.line_stations ls ON ls.station_id = s.id\r\n  JOIN staging.lines l ON l.id = ls.line_id\r\n  WHERE l.name IN (${line:sqlstring})\r\n)\r\n  AND $__timeFilter(production_day);"
    }
   ]
  },
  {
   "title": "MTBF / MTTR",
   "type": "bargauge",
   "description": "MTBF (Mean Time Between Failures): average time between two failures (the higher, the better).\n\nMTTR (Mean Time To Repair): average repair time after a failure (the lower, the better).\n\nIndustrial target: MTBF > 100h, MTTR < 4h.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    m.station_name,\r\n    m.mtbf_hours AS \"Mean Time Between Failures\",\r\n    t.mttr_hours AS \"Mean Time To Repair\"\r\nFROM public.mtbf_kpi m\r\nJOIN public.mttr_kpi t ON m.station_id = t.station_id\r\nWHERE m.station_name IS NOT NULL\r\n    AND m.mtbf_hours IS NOT NULL\r\nORDER BY m.mtbf_hours ASC"
    }
   ]
  },
  {
   "title": "Quality Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n    DATE_TRUNC('week', production_day)::date AS \"time\",\r\n    SUM(good_count)  AS \"Pass\",\r\n    SUM(fail_count)  AS \"Fail\",\r\n    SUM(scrap_count) AS \"Scrap\"\r\nFROM public.defect_rate_kpi\r\nWHERE station_name IN (\r\n    SELECT s.name FROM staging.stations s\r\n    JOIN staging.line_stations ls ON ls.station_id = s.id\r\n    JOIN staging.lines l ON l.id = ls.line_id\r\n    WHERE l.name IN (${line:sqlstring})\r\n  )\r\n  AND $__timeFilter(production_day)\r\nGROUP BY DATE_TRUNC('week', production_day)\r\nORDER BY DATE_TRUNC('week', production_day);"
    }
   ]
  },
  {
   "title": "First Pass Yield (FPY)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n\r\n(\r\n    SELECT ROUND(AVG(NULLIF(quality_pct,0)),1) as \"Quality Rate\"\r\n    FROM public.quality_kpi\r\n    WHERE station_name IN (\r\n      SELECT s.name FROM staging.stations s\r\n      JOIN staging.line_stations ls ON ls.station_id = s.id\r\n      JOIN staging.lines l ON l.id = ls.line_id\r\n      WHERE l.name IN (${line:sqlstring})\r\n    )\r\n      AND $__timeFilter(production_day)\r\n) AS \"Quality Rate\";"
    }
   ]
  },
  {
   "title": "Quality Assessment",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n  AVG(defect_rate_pct) AS \"Defect Rate (moyenne)\"\r\nFROM public.defect_rate_kpi\r\nWHERE station_name IN (\r\n    SELECT s.name FROM staging.stations s\r\n    JOIN staging.line_stations ls ON ls.station_id = s.id\r\n    JOIN staging.lines l ON l.id = ls.line_id\r\n    WHERE l.name IN (${line:sqlstring})\r\n  )\r\n  AND $__timeFilter(production_day);"
    }
   ]
  },
  {
   "title": "Top Defect Stations Analysis",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    station_name AS \"Station\",\r\n    ROUND(AVG(defect_rate_pct),2) AS \"Defect Rate (%)\"\r\nFROM public.defect_rate_kpi\r\n    WHERE station_name IN (\r\n        SELECT s.name FROM staging.stations s\r\n        JOIN staging.line_stations ls ON ls.station_id = s.id\r\n        JOIN staging.lines l ON l.id = ls.line_id\r\n        WHERE l.name IN (${line:sqlstring})\r\n      )\r\n      AND $__timeFilter(production_day)\r\nGROUP BY station_name\r\nORDER BY \"Defect Rate (%)\" DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Production: Pass / Fail / Scrap by Week",
   "type": "barchart",
   "description": "Daily evolution of produced parts by status.\n* Pass = compliant/good parts (good_count)\n* Fail = repairable defective parts (fail_count)\n* Scrap = non-recoverable rejected parts (scrap_count)",
   "gridPos": { "h": 17, "w": 14, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n    DATE_TRUNC('week', production_day)::date AS \"time\",\r\n    ROUND(100.0 * SUM(good_count)  / NULLIF(SUM(total_bookings), 0), 2) AS \"Pass\",\r\n    ROUND(100.0 * SUM(fail_count)  / NULLIF(SUM(total_bookings), 0), 2) AS \"Fail\",\r\n    ROUND(100.0 * SUM(scrap_count) / NULLIF(SUM(total_bookings), 0), 2) AS \"Scrap\"\r\nFROM public.defect_rate_kpi\r\n    WHERE station_name IN (\r\n        SELECT s.name FROM staging.stations s\r\n        JOIN staging.line_stations ls ON ls.station_id = s.id\r\n        JOIN staging.lines l ON l.id = ls.line_id\r\n        WHERE l.name IN (${line:sqlstring})\r\n    )\r\n  AND $__timeFilter(production_day)\r\nGROUP BY DATE_TRUNC('week', production_day)\r\nORDER BY DATE_TRUNC('week', production_day);"
    }
   ]
  },
  {
   "title": "Monthly Scrap Rate Trend",
   "type": "barchart",
   "description": "Displays the monthly evolution of scrap generation to monitor long-term quality performance.",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    date_trunc('month', production_day::timestamp) AS \"time\",\r\n    AVG(scrap_rate_pct) AS scrap_rate\r\nFROM public.scrap_by_day_kpi\r\n    WHERE station_name IN (\r\n        SELECT s.name FROM staging.stations s\r\n        JOIN staging.line_stations ls ON ls.station_id = s.id\r\n        JOIN staging.lines l ON l.id = ls.line_id\r\n        WHERE l.name IN (${line:sqlstring})\r\n      )\r\n  AND $__timeFilter(production_day::timestamp)\r\nGROUP BY 1\r\nORDER BY 1;"
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         3,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "A" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "type": "classic_conditions"
    }
   ]
  },
  {
   "title": "Quality Trend",
   "type": "timeseries",
   "description": "Quality rate trend over time.",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    production_day AS \"time\",\r\n    100 - defect_rate_pct AS \"Quality Rate (%)\",\r\n\r\n    (\r\n      SELECT MIN(100 - defect_rate_pct)\r\n      FROM public.defect_rate_kpi\r\n      WHERE station_name IN (\r\n        SELECT s.name FROM staging.stations s\r\n        JOIN staging.line_stations ls ON ls.station_id = s.id\r\n        JOIN staging.lines l ON l.id = ls.line_id\r\n        WHERE l.name IN (${line:sqlstring})\r\n      )\r\n      AND $__timeFilter(production_day)\r\n    ) AS \"Min\",\r\n\r\n    (\r\n      SELECT MAX(100 - defect_rate_pct)\r\n      FROM public.defect_rate_kpi\r\n      WHERE station_name IN (\r\n        SELECT s.name FROM staging.stations s\r\n        JOIN staging.line_stations ls ON ls.station_id = s.id\r\n        JOIN staging.lines l ON l.id = ls.line_id\r\n        WHERE l.name IN (${line:sqlstring})\r\n      )\r\n      AND $__timeFilter(production_day)\r\n    ) AS \"Max\",\r\n\r\n    95 AS \"World-class\"\r\n\r\nFROM public.defect_rate_kpi\r\nWHERE station_name IN (\r\n  SELECT s.name FROM staging.stations s\r\n  JOIN staging.line_stations ls ON ls.station_id = s.id\r\n  JOIN staging.lines l ON l.id = ls.line_id\r\n  WHERE l.name IN (${line:sqlstring})\r\n)\r\nAND $__timeFilter(production_day)\r\nORDER BY production_day;"
    }
   ]
  },
  {
   "title": "Daily Scrap Rate Trend",
   "type": "timeseries",
   "description": "Tracks daily scrap generation to identify quality losses and process instability.",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  production_day AS \"time\",\r\n  scrap_rate_pct AS \"Scrap Rate\"\r\nFROM public.scrap_by_day_kpi\r\nWHERE station_name IN ($station)\r\n  AND $__timeFilter(production_day)\r\nORDER BY production_day;"
    }
   ]
  }
 ]
}