{
 "title": "🏭 Routing Intelligence & Flow Optimization",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "part_number",
    "query": "SELECT DISTINCT part_number\nFROM public.production_routing_overview\nORDER BY 1;"
   },
   {
    "name": "workplan_type",
    "query": "SELECT DISTINCT workplan_type\nFROM public.production_routing_overview\nORDER BY 1;"
   },
   {
    "name": "step_type",
    "query": "SELECT DISTINCT step_type\nFROM public.production_routing_overview\nORDER BY 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total work orders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT COUNT(DISTINCT workorder_id) AS total_workorders\r\nFROM public.production_routing_overview;"
    }
   ]
  },
  {
   "title": "Routing Efficiency Score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\nROUND(\r\n    AVG(\r\n        te_machine /\r\n        NULLIF(te_machine + wait_time + transport_time,0)\r\n    ) * 100,\r\n2) AS routing_efficiency\r\nFROM public.production_routing_overview\r\nWHERE part_number IN (${part_number:sqlstring})   \r\n"
    }
   ]
  },
  {
   "title": "Flow Time Breakdown",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    ROUND(\r\n        AVG(\r\n            COALESCE(te_machine,0)\r\n            / NULLIF(\r\n                COALESCE(te_machine,0)\r\n                + COALESCE(wait_time,0)\r\n                + COALESCE(transport_time,0),\r\n                0\r\n            )\r\n        ) * 100,\r\n        2\r\n    ) AS routing_efficiency\r\nFROM public.production_routing_overview\r\nWHERE part_number IN (${part_number:sqlstring})\r\n  AND workplan_type IN (${workplan_type:sqlstring})\r\n  AND step_type IN (${step_type:sqlstring});"
    }
   ]
  },
  {
   "title": "Work orders par type de routing",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    workplan_type,\r\n    COUNT(DISTINCT workorder_id) AS total\r\nFROM public.production_routing_overview\r\nGROUP BY workplan_type\r\nORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Work orders par status ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    workorder_status,\r\n    COUNT(DISTINCT workorder_id) AS total\r\nFROM public.production_routing_overview\r\nGROUP BY workorder_status\r\nORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Routing Bottlenecks",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    workstep_desc,\r\n    ROUND(AVG(wait_time)::numeric,2) AS avg_wait_time\r\nFROM public.production_routing_overview\r\nGROUP BY workstep_desc\r\nORDER BY avg_wait_time DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 opérations les plus longues",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    workstep_desc,\r\n    ROUND(AVG(\r\n        COALESCE(setup_time,0)\r\n        + COALESCE(te_machine,0)\r\n        + COALESCE(wait_time,0)\r\n        + COALESCE(transport_time,0)\r\n    )::numeric, 2) AS avg_step_time\r\nFROM public.production_routing_overview\r\nWHERE part_number IN (${part_number:sqlstring})\r\n  AND workplan_type IN (${workplan_type:sqlstring})\r\n  AND step_type IN (${step_type:sqlstring})\r\nGROUP BY workstep_desc\r\nORDER BY avg_step_time DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Détail du routing par opération",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    part_number,\r\n    part_description,\r\n    workstep_no,\r\n    workstep_desc,\r\n    setup_time,\r\n    te_machine AS temps_Machine,\r\n    wait_time,\r\n    transport_time AS temps_Transfert,\r\n    step_type\r\nFROM public.production_routing_overview\r\nWHERE part_number IN (${part_number:sqlstring})\r\n  AND step_type IN (${step_type:sqlstring})\r\nORDER BY workstep_no;"
    }
   ]
  }
 ]
}